fieldLayouts:
  f2e75ab6-0407-4c16-b3ba-456c69ea72c3:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            warning: null
            width: 100
          -
<<<<<<< Updated upstream
=======
            elementCondition: null
            fieldUid: 9a90cbf7-2008-45ab-8dcb-1d7a961563c0 # Afbeelding
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 95782200-d0aa-45a8-80ae-e218117ce73a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
>>>>>>> Stashed changes
            fieldUid: db40784b-08c3-47f5-bba6-620385411e85 # Kleine blok
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1919357a-9336-4b00-8f56-e9da754f13a9 # Locatie
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 86a66aa1-8528-4e35-a5ea-3454fc23800d # Soort
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8eccee9f-28f1-41fe-9b86-4a793dde5b61 # Start uur
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5c83c045-1cf1-4135-92af-bbea0f0eb952 # Eind uur
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3905d91b-dc37-4488-9150-d0956af46de0 # Artikel link
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: programmaDetails
hasTitleField: true
name: 'Programma details'
section: 9868968d-46de-4ab8-bd19-48bcd95d03a4 # Programma details
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
