defaultPlacement: end
enableVersioning: true
handle: mutationProgramDetails
name: 'Programma details'
propagationMethod: all
siteSettings:
  8e92c4bf-d4fb-49f5-9833-4e91fb775669: # Mutation
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  52a14414-bcd2-4106-8c09-8dec1e08e4ef: # Mutation-En
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 8b60ea00-23ef-458b-8d0b-938e6886fd26
type: structure
