columnSuffix: null
contentColumnType: text
handle: paragraph
instructions: ''
name: Paragraaf
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: 12d25984-f2d6-4041-9f35-32e8b8645969 # Simple 2
  columnType: text
  defaultTransform: ''
  enableSourceEditingForNonAdmins: true
  purifierConfig: ''
  purifyHtml: '1'
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
